apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server-discovery
  name: server-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-discovery
  strategy: {}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
      labels:
        io.kompose.service: server-discovery
    spec:
      containers:
      - env:
        - name: CONFIG_URI
          value: http://config-server:8888
        - name: ACTUATOR_PASSWORD
          value: "vault:secret/data/actuator#ACTUATOR_PASSWORD"
        - name: EUREKA_URL
          value: "vault:secret/data/server-discovery#EUREKA_URL"
        - name: DASHBOARD_PASSWORD
          value: "vault:secret/data/server-discovery#DASHBOARD_PASSWORD"
        - name: EUREKA_PASSWORD
          value: "vault:secret/data/server-discovery#EUREKA_PASSWORD"
        - name: ENV
          value: dev
        image: 'szastarek/food-delivery-server-discovery:0.0.1-SNAPSHOT'
        imagePullPolicy: ""
        name: server-discovery
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
