language: java
jdk: openjdk11
install: true
script:
  "server-discovery/gradlew build -p server-discovery && gateway/gradlew build -p gateway && config-server/gradlew build -p config-server &&  account-service/gradlew build -p account-service"