version: '3.7'

services:

  elasticsearch:
    image: szastarek/food-delivery-elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      food-delivery-net:
        aliases:
          - "elasticsearch"

  logstash:
    image: szastarek/food-delivery-logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      food-delivery-net:
        aliases:
          - logstash
    depends_on:
      - elasticsearch

  kibana:
    image: szastarek/food-delivery-kibana
    ports:
      - "5601:5601"
    networks:
      food-delivery-net:
        aliases:
          - "kibana"
    depends_on:
      - elasticsearch

  config-server-db:
    image: szastarek/food-delivery-config-server-db
    container_name: config-server-db
    networks:
      samplenet:
        aliases:
          - "config-server-db"

  account-service-db:
    image: szastarek/food-delivery-account-service-db
    container_name: account-service-db
    networks:
      samplenet:
        aliases:
          - "account-service-db"

  company-service-db:
    image: szastarek/food-delivery-company-service-db
    container_name: company-service-db
    networks:
      food-delivery-net:
        aliases:
          - "company-service-db"

  config-server:
    image: szastarek/food-delivery-config-server:${TAG}
    container_name: config-server
    environment:
      - ENV=prod,jdbc
      - logging.logstash.enabled=true
      - logging.logstash.url=logstash:5000
      - spring.datasource.hikari.maximum-pool-size=10
      - spring.datasource.hikari.connection-timeout=5000
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://config-server-db:5432/application-properties
      - spring.datasource.username=config_user
      - spring.datasource.password=z8BFsHAQ4dGrm8R12SQCoTvG
    depends_on:
      - config-server-db
    networks:
      samplenet:
        aliases:
          - "config-server"

  server-discovery:
    image: szastarek/food-delivery-server-discovery:${TAG}
    container_name: server-discovery
    environment:
        - CONFIG_URI=http://config-server:8888
        - ENV=prod
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      samplenet:
        aliases:
          - "server-discovery"

  gateway:
    image: szastarek/food-delivery-gateway:${TAG}
    container_name: gateway
    environment:
        - CONFIG_URI=http://config-server:8888
        - EUREKA_URL=http://server-discovery:8761/eureka/
        - ENV=prod
        - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
        - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
    ports:
      - 8060:8060
    depends_on:
      - config-server
    networks:
      samplenet:
        aliases:
          - "gateway"

  account-service:
    image: szastarek/food-delivery-account-service:${TAG}
    container_name: account-service
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://server-discovery:8761/eureka/
      - ENV=prod
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - DATABASE_URI=mongodb://mongoadmin:secret@account-service-db:27017/account?authSource=admin
    depends_on:
      - config-server
      - account-service-db
    networks:
      samplenet:
        aliases:
          - "account-service"

  company-service:
    image: szastarek/food-delivery-company-service:${TAG}
    container_name: company-service
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://server-discovery:8761/eureka/
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - DATABASE_URI=mongodb://mongoadmin:secret@company-service-db:27017/company?authSource=admin
    depends_on:
      - config-server
      - company-service-db
    networks:
      food-delivery-net:
        aliases:
          - "company-service"

networks:
  samplenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
