apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - image: szastarek/food-delivery-grafana
        imagePullPolicy: ""
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
