apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "3030"
    port: 3030
    targetPort: 3000
  selector:
    io.kompose.service: grafana
