apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "8060"
    port: 8060
    targetPort: 8060
  selector:
    io.kompose.service: gateway
