apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: blackbox-exporter
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blackbox-exporter
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: blackbox-exporter
    spec:
      containers:
      - image: prom/blackbox-exporter
        imagePullPolicy: ""
        name: black-exporter
        ports:
        - containerPort: 9115
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
