version: '3.7'

services:

  elasticsearch:
    image: szastarek/food-delivery-elasticsearch
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      food-delivery-net:
        aliases:
          - "elasticsearch"

  logstash:
    image: szastarek/food-delivery-logstash
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      food-delivery-net:
        aliases:
          - logstash
    depends_on:
      - elasticsearch

  kibana:
    image: szastarek/food-delivery-kibana
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      food-delivery-net:
        aliases:
          - "kibana"
    depends_on:
      - elasticsearch

  prometheus:
    image: szastarek/food-delivery-prometheus
    container_name: prometheus
    environment:
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      food-delivery-net:
        aliases:
          - "prometheus"

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: black-exporter
    ports:
      - 9115:9115
    networks:
      food-delivery-net:
        aliases:
          - "blackbox-exporter"

  grafana:
    image: szastarek/food-delivery-grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3030:3000
    networks:
      food-delivery-net:
        aliases:
          - "grafana"

  config-server-db:
    image: szastarek/food-delivery-config-server-db
    container_name: config-server-db
    environment:
      - POSTGRES_DB=application-properties
      - POSTGRES_USER=config_user
      - POSTGRES_PASSWORD=z8BFsHAQ4dGrm8R12SQCoTvG
    ports:
      - 5432:5432
    networks:
      food-delivery-net:
        aliases:
          - "config-server-db"

  account-service-db:
    image: szastarek/food-delivery-account-service-db
    container_name: account-service-db
    environment:
      - MONGO_INITDB_DATABASE=account
      - MONGO_INITDB_ROOT_USERNAME=account_user
      - MONGO_INITDB_ROOT_PASSWORD=EtQ43076pyyuaY9rBRtc3opV
    ports:
      - 27017:27017
    networks:
      food-delivery-net:
        aliases:
          - "account-service-db"

  company-service-db:
    image: szastarek/food-delivery-company-service-db
    container_name: company-service-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=company_user
      - MONGO_INITDB_ROOT_PASSWORD=cmP53UKav16xYxK9Jx2J9Q9U
      - MONGO_INITDB_DATABASE=company
    ports:
      - 27016:27017
    networks:
      food-delivery-net:
        aliases:
          - "company-service-db"

  config-server:
    image: szastarek/food-delivery-config-server:${TAG}
    container_name: config-server
    environment:
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - logging.logstash.enabled=true
      - logging.logstash.url=logstash:5000
      - spring.datasource.hikari.connection-timeout=5000
      - spring.datasource.hikari.maximum-pool-size=10
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://config-server-db:5432/application-properties
      - spring.datasource.username=config_user
      - spring.datasource.password=z8BFsHAQ4dGrm8R12SQCoTvG
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - ENV=prod,jdbc
    ports:
      - 8888:8888
    depends_on:
      - config-server-db
    networks:
      food-delivery-net:
        aliases:
          - "config-server"

  server-discovery:
    image: szastarek/food-delivery-server-discovery:${TAG}
    container_name: server-discovery
    environment:
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - CONFIG_URI=http://config-server:8888
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - DASHBOARD_PASSWORD=password
      - EUREKA_PASSWORD=password
      - ENV=dev
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      food-delivery-net:
        aliases:
          - "server-discovery"

  gateway:
    image: szastarek/food-delivery-gateway:${TAG}
    container_name: gateway
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - ENV=dev,swagger
    ports:
      - 8060:8060
    depends_on:
      - config-server
    networks:
      food-delivery-net:
        aliases:
          - "gateway"

  account-service:
    image: szastarek/food-delivery-account-service:${TAG}
    container_name: account-service
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - DATABASE_URI=mongodb://account_user:EtQ43076pyyuaY9rBRtc3opV@account-service-db:27017/account?authSource=admin
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - ENV=dev,swagger
    depends_on:
      - config-server
      - account-service-db
    networks:
      food-delivery-net:
        aliases:
          - "account-service"

  company-service:
    image: szastarek/food-delivery-company-service:${TAG}
    container_name: company-service
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - DATABASE_URI=mongodb://company_user:cmP53UKav16xYxK9Jx2J9Q9U@company-service-db:27017/company?authSource=admin
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - ENV=dev,swagger
    depends_on:
      - config-server
      - company-service-db
    networks:
      food-delivery-net:
        aliases:
          - "company-service"

  okta-adapter:
    image: szastarek/food-delivery-okta-adapter:${TAG}
    container_name: okta-adapter
    environment:
      - CONFIG_URI=http://config-server:8888
      - EUREKA_URL=http://account_eureka:password@server-discovery:8761/eureka/
      - OKTA_CLIENT_ID=0oaqf5gc3jy2DHcYI0h7
      - OKTA_ISSUER=https://dev-826281.oktapreview.com/oauth2/default
      - OKTA_DOMAIN_URL=https://dev-826281.oktapreview.com/
      - OKTA_API_TOKEN=00-huO9jqNlI-jRAwgSjhvTMI_4Og17V07fvnHjehO
      - ACTUATOR_PASSWORD=iN09KtaW59dqeRylgZFV4aSZ
      - ENV=dev
    depends_on:
      - config-server
    networks:
      food-delivery-net:
        aliases:
          - "okta-adapter"

networks:
  food-delivery-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
