apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: company-service-db
  name: company-service-db
spec:
  ports:
  - name: "27016"
    port: 27016
    targetPort: 27017
  selector:
    io.kompose.service: company-service-db
