apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: account-service-db
  name: account-service-db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: account-service-db
