apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: account-service-db
  name: account-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service-db
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: account-service-db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: account
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: EtQ43076pyyuaY9rBRtc3opV
        - name: MONGO_INITDB_ROOT_USERNAME
          value: account_user
        image: szastarek/food-delivery-account-service-db
        imagePullPolicy: ""
        name: account-service-db
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
