apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy: {}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
      labels:
        io.kompose.service: account-service
    spec:
      containers:
      - env:
        - name: CONFIG_URI
          value: http://config-server:8888
        - name: ENV
          value: dev,swagger
        - name: EUREKA_URL
          value: "vault:secret/data/server-discovery#EUREKA_URL"
        - name: ACTUATOR_PASSWORD
          value: "vault:secret/data/actuator#ACTUATOR_PASSWORD"
        - name: DATABASE_URI
          value: "vault:secret/data/account-service#DATABASE_URI"
        - name: OKTA_CLIENT_ID
          value: 0oaqf5gc3jy2DHcYI0h7
        - name: OKTA_ISSUER
          value: https://dev-826281.oktapreview.com/oauth2/default
        - name: KAFKA_URI
          value: mail-sender-kafka:9092
        image: 'szastarek/food-delivery-account-service:0.0.1-SNAPSHOT'
        imagePullPolicy: ""
        name: account-service
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
