apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: account-service-db
  name: account-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service-db
  strategy: {}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
      labels:
        io.kompose.service: account-service-db
    spec:
      containers:
      - env:
          - name: MONGO_INITDB_DATABASE
            value: "vault:secret/data/account-service#MONGO_INITDB_DATABASE"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "vault:secret/data/account-service#MONGO_INITDB_ROOT_USERNAME"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "vault:secret/data/account-service#MONGO_INITDB_ROOT_PASSWORD"
        image: szastarek/food-delivery-account-service-db
        imagePullPolicy: ""
        name: account-service-db
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
