
server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/config-server-db
    driver-class-name: org.postgresql.Driver
    username: config_user
    password: z8BFsHAQ4dGrm8R12SQCoTvG
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  profiles:
    active:
      - jdbc
