server:
  port: 8888

spring:
  application:
    name: config-server

  datasource:
    url: ${CONFIG_DB_URI:jdbc:postgresql://localhost:5432/application-properties}
    driver-class-name: org.postgresql.Driver
    username: config_user
    password: z8BFsHAQ4dGrm8R12SQCoTvG
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  profiles:
    active:
      - jdbc

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  logstash:
    enabled: true
    url: logstash:5000
    ignorePatterns: /(actuator|swagger|webjars).*

actuator:
  username: account_actuator
  password: ${ACTUATOR_PASSWORD}
  authority: ACTUATOR
  path: /actuator/**
