apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mail-sender-kafka
  name: mail-sender-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: mail-sender-kafka
  type: LoadBalancer
