apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mail-sender
  name: mail-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-sender
  strategy: {}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
      labels:
        io.kompose.service: mail-sender
    spec:
      containers:
        - env:
            - name: CONFIG_URI
              value: http://config-server:8888
            - name: KAFKA_URI
              value: mail-sender-kafka:9092
            - name: ACTUATOR_PASSWORD
              value: "vault:secret/data/actuator#ACTUATOR_PASSWORD"
            - name: EUREKA_URL
              value: "vault:secret/data/server-discovery#EUREKA_URL"
            - name: SENDGRID_API_KEY
              value: "vault:secret/data/sendgrid#SENDGRID_API_KEY"
            - name: ENV
              value: dev
          image: 'szastarek/food-delivery-mail-sender:0.0.1-SNAPSHOT'
          imagePullPolicy: ""
          name: mail-sender
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
