apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mail-sender-kafka
  name: mail-sender-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-sender-kafka
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mail-sender-kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: mail-sender-kafka
            - name: KAFKA_ADVERTISED_PORT
              value: '9092'
            - name: ADVERTISED_LISTENERS
              value: PLAINTEXT://mail-sender-kafka:9092
            - name: KAFKA_CREATE_TOPICS
              value: activate-user:1:1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.12-2.2.1
          imagePullPolicy: ""
          name: mail-sender-kafka
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
