apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: szastarek/food-delivery-logstash
        imagePullPolicy: ""
        name: logstash
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
